package br.com.agenda.model;
// Generated 24/06/2019 23:04:18 by Hibernate Tools 4.3.1



/**
 * Contato generated by hbm2java
 */
public class Contato  implements java.io.Serializable {


     private Integer idContato;
     private String nome;
     private String cargo;
     private String empresa;
     private String dataAniversario;

    public Contato() {
    }

    public Contato(String nome, String cargo, String empresa, String dataAniversario) {
       this.nome = nome;
       this.cargo = cargo;
       this.empresa = empresa;
       this.dataAniversario = dataAniversario;
    }
   
    public Integer getIdContato() {
        return this.idContato;
    }
    
    public void setIdContato(Integer idContato) {
        this.idContato = idContato;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getDataAniversario() {
        return this.dataAniversario;
    }
    
    public void setDataAniversario(String dataAniversario) {
        this.dataAniversario = dataAniversario;
    }




}


