package br.com.agenda.model;
// Generated 24/06/2019 23:04:18 by Hibernate Tools 4.3.1



/**
 * Meiocontato generated by hbm2java
 */
public class Meiocontato  implements java.io.Serializable {


     private Integer idMeioContato;
     private String tipoContato;
     private String conteudo;

    public Meiocontato() {
    }

    public Meiocontato(String tipoContato, String conteudo) {
       this.tipoContato = tipoContato;
       this.conteudo = conteudo;
    }
   
    public Integer getIdMeioContato() {
        return this.idMeioContato;
    }
    
    public void setIdMeioContato(Integer idMeioContato) {
        this.idMeioContato = idMeioContato;
    }
    public String getTipoContato() {
        return this.tipoContato;
    }
    
    public void setTipoContato(String tipoContato) {
        this.tipoContato = tipoContato;
    }
    public String getConteudo() {
        return this.conteudo;
    }
    
    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }




}


